targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/services/graphql/schemas/restaurant_schema.graphql
              querires_glob: lib/services/graphql/queries/**.graphql
              output: lib/services/graphql/schemas/gql_api.dart
              naming_scheme: simple
